import { Inter } from "next/font/google";
import "./globals.css";
import styles from '../components/PostCard.module.css'
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog App",
  description: "Generated by Blog ",
};

let header = (
  <header className={styles.body}>
    <Link href={'/'}> 
    <h1>My Blog Post</h1>
    </Link>

  </header>
)


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {header}
      {children}

      </body>
      
    </html>
  );
}
